import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from dotenv import load_dotenv

# Resolve repository root
REPO_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=REPO_ROOT / ".env")

PROMPT_FILE = REPO_ROOT / "research" / "prompt_template.txt"
OUTPUT_FILE = REPO_ROOT / "research" / "report.md"

LITEROUTER_PORT = os.getenv("LITEROUTER_PORT", "7766")
LITEROUTER_KEY = os.getenv("LITEROUTER_AUTH_KEY", "sk-lr-8f2a9e3b1c4d7e5f")
GATEWAY_URL = f"http://localhost:{LITEROUTER_PORT}/v1beta/interactions"


def run_deep_research():
    if not PROMPT_FILE.exists():
        print(f"❌ Error: Prompt template not found at {PROMPT_FILE}")
        sys.exit(1)

    prompt_content = PROMPT_FILE.read_text(encoding="utf-8").strip()
    print("==================================================================")
    print("🔬 DEEP RESEARCH AGENT (via LiteRouter + Antigravity)")
    print("==================================================================")
    print(f"📍 Target Gateway: {GATEWAY_URL}")
    print(f"📄 Reading Prompt: {PROMPT_FILE}")
    print("------------------------------------------------------------------")
    print(prompt_content[:300] + ("..." if len(prompt_content) > 300 else ""))
    print("==================================================================\n")

    payload = {
        "agent": "antigravity-preview-05-2026",
        "input": prompt_content,
        "environment": "remote",
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LITEROUTER_KEY}",
    }

    req = urllib.request.Request(
        GATEWAY_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST",
    )

    print("🚀 Dispatching request to Antigravity Agent (Google Cloud Remote Sandbox)...")
    print("⏳ This multi-step execution takes approximately 1-3 minutes. Please wait...\n")

    start_time = time.time()
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            elapsed = time.time() - start_time
            print(f"✅ Response received in {elapsed:.1f} seconds (HTTP {resp.status})!")

            res_body = resp.read().decode("utf-8")
            res_json = json.loads(res_body)

            # Extract output text / step summaries
            output_text = res_json.get("output_text", "")
            steps = res_json.get("steps", [])

            formatted_report = []
            formatted_report.append("# Deep Research Report: AI Bubble Analysis\n\n")
            formatted_report.append("*Generated by Antigravity Agent (`antigravity-preview-05-2026`) via LiteRouter*\n")
            status = res_json.get("status", "completed")
            formatted_report.append(f"*Execution Time: {elapsed:.1f}s | Status: {status}*\n\n")
            formatted_report.append("---\n\n")

            if output_text:
                formatted_report.append("## Executive Report\n\n")
                formatted_report.append(output_text.strip())
                formatted_report.append("\n\n---\n\n")

            if steps:
                formatted_report.append("## Step-by-Step Research Findings\n\n")
                for i, s in enumerate(steps, 1):
                    summary = s.get("summary", "")
                    if isinstance(summary, list):
                        summary_str = "\n".join([t.get("text", "") for t in summary if isinstance(t, dict)]).strip()
                    else:
                        summary_str = str(summary).strip()

                    # Extract any parts/text in step output if present
                    output_parts = []
                    for part in s.get("output", {}).get("parts", []):
                        if isinstance(part, dict) and "text" in part:
                            output_parts.append(part["text"].strip())
                    
                    output_str = "\n\n".join(output_parts)

                    if summary_str or output_str:
                        formatted_report.append(f"### Phase {i}\n\n")
                        if summary_str:
                            formatted_report.append(f"{summary_str}\n\n")
                        if output_str:
                            formatted_report.append(f"{output_str}\n\n")

            final_report_str = "".join(formatted_report)
            OUTPUT_FILE.write_text(final_report_str, encoding="utf-8")

            print("\n🎉 Deep Research Complete!")
            print(f"📄 Report written to: {OUTPUT_FILE}")
            print(f"📊 Usage stats: {json.dumps(res_json.get('usage', {}), indent=2)}")

    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="ignore")
        print(f"❌ HTTP Error {e.code}: {err_body[:500]}")
    except Exception as e:
        print(f"❌ Execution Error: {e}")


if __name__ == "__main__":
    run_deep_research()
