#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# kill-ipv6.sh: Safe IPv6 Disablement for WSL2 (Preserves Localhost/Loopback)
# ==============================================================================

MODE="${1:-apply}"

SYSCTL_CONF_FILE="/etc/sysctl.d/99-disable-ipv6.conf"
BASHRC_FILE="$HOME/.bashrc"
NODE_DIRECTIVE='export NODE_OPTIONS="--dns-result-order=ipv4first"'

if [ "$MODE" = "--restore" ] || [ "$MODE" = "restore" ]; then
    echo "========================================================"
    echo " Restoring IPv6 to Default Kernel State"
    echo "========================================================"
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
    sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
    if [ -f "$SYSCTL_CONF_FILE" ]; then
        sudo rm -f "$SYSCTL_CONF_FILE"
        echo "  -> Removed $SYSCTL_CONF_FILE"
    fi
    echo "  -> IPv6 has been restored to default enabled state."
    exit 0
fi

echo "========================================================"
echo " [1/3] Applying Kernel-Level IPv6 Disablement"
echo "========================================================"

# CRITICAL: Disable external IPv6, but KEEP loopback (lo) enabled (disable_ipv6=0).
# Disabling loopback breaks local IPC in Node 20 (OpenCode2, MCP servers, Vite).
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0

echo ""
echo "========================================================"
echo " [2/3] Persisting Configuration Across WSL Restarts"
echo "========================================================"

sudo tee "$SYSCTL_CONF_FILE" > /dev/null << 'EOF'
# Generated by literouter scripts/kill-ipv6.sh
# Disables external IPv6 routing while preserving loopback IPC
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 0
EOF

sudo sysctl --system > /dev/null 2>&1 || sudo sysctl -p "$SYSCTL_CONF_FILE"
echo "  -> Saved persistent rule to $SYSCTL_CONF_FILE"

# Clean up and ensure NODE_OPTIONS is correctly set in ~/.bashrc
if grep -Fxq "$NODE_DIRECTIVE" "$BASHRC_FILE" 2>/dev/null; then
    echo "  -> Node.js DNS order already set in $BASHRC_FILE"
else
    echo "" >> "$BASHRC_FILE"
    echo "# Force Node.js (Claude Code, SDKs) to prioritize IPv4" >> "$BASHRC_FILE"
    echo "$NODE_DIRECTIVE" >> "$BASHRC_FILE"
    echo "  -> Appended Node.js IPv4 priority to $BASHRC_FILE"
fi

echo ""
echo "========================================================"
echo " [3/3] Verification & Status Check"
echo "========================================================"

ALL_DISABLED=$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null || echo "0")
DEFAULT_DISABLED=$(cat /proc/sys/net/ipv6/conf/default/disable_ipv6 2>/dev/null || echo "0")
LO_DISABLED=$(cat /proc/sys/net/ipv6/conf/lo/disable_ipv6 2>/dev/null || echo "0")

echo "  Status:"
echo "  - External IPv6 (all/default): $([ "$ALL_DISABLED" = "1" ] && echo "DISABLED (OK)" || echo "ENABLED")"
echo "  - Local Loopback (lo):        $([ "$LO_DISABLED" = "0" ] && echo "ACTIVE (OK for OpenCode2 & Localhost IPC)" || echo "DISABLED (Risky)")"

echo ""
echo "========================================================"
echo " Done! Run: source ~/.bashrc"
echo " (To undo at any time, run: ./scripts/kill-ipv6.sh --restore)"
echo "========================================================"
