import { describe, expect, it, beforeEach } from "bun:test";
import {
  OPENCODE_SESSION_REGEX,
  isValidOpenCodeSessionId,
  buildZenHeaders,
  getZenProbeTools,
  adaptZenPayload,
  accumulateZenStreamToCompletion,
} from "../../../src/engine/zen";
import { generateOpenCodeSessionId } from "../../../src/engine/session_id";
import { getProviderConfig, initProviderRegistry } from "../../../src/config/providers";

describe("src/engine/zen.ts", () => {
  beforeEach(() => {
    initProviderRegistry();
  });
  describe("OPENCODE_SESSION_REGEX and isValidOpenCodeSessionId", () => {
    it("validates session IDs generated by generateOpenCodeSessionId", () => {
      for (let i = 0; i < 10; i++) {
        const id = generateOpenCodeSessionId();
        expect(OPENCODE_SESSION_REGEX.test(id)).toBe(true);
        expect(isValidOpenCodeSessionId(id)).toBe(true);
      }
    });

    it("validates known well-formed OpenCode session IDs", () => {
      const valid = "ses_123456788ffeAbCdEfGhIjKlMn";
      expect(isValidOpenCodeSessionId(valid)).toBe(true);
      const standardExample = "ses_123456788ffeaAbBcCdDeEfFgG";
      expect(isValidOpenCodeSessionId(standardExample)).toBe(true);
      expect(OPENCODE_SESSION_REGEX.test(standardExample)).toBe(true);
    });

    it("rejects invalid session IDs", () => {
      expect(isValidOpenCodeSessionId("")).toBe(false);
      expect(isValidOpenCodeSessionId("ses_invalid")).toBe(false);
      expect(isValidOpenCodeSessionId("ses_123456787ffeAbCdEfGhIjKlMn")).toBe(false); // wrong marker (7ffe instead of 8ffe)
      expect(isValidOpenCodeSessionId("ses_1234567g8ffeAbCdEfGhIjKlMn")).toBe(false); // non-hex character in timestamp
      expect(isValidOpenCodeSessionId("ses_123456788ffeAbCdEfGhIjKlM")).toBe(false); // 13 chars in tail
      expect(isValidOpenCodeSessionId("ses_123456788ffeAbCdEfGhIjKlMnO")).toBe(false); // 15 chars in tail
      expect(isValidOpenCodeSessionId("ses_123456788ffeAbCdEfGhIjKlM_")).toBe(false); // non-base62 in tail
      expect(isValidOpenCodeSessionId(12345 as unknown as string)).toBe(false);
    });
  });

  describe("buildZenHeaders", () => {
    it("merges configured attribution headers from getProviderConfig('zn')", () => {
      const znConfig = getProviderConfig("zn");
      const headers = buildZenHeaders();

      for (const [key, val] of Object.entries(znConfig?.headers ?? {})) {
        expect(headers[key]).toBe(val);
      }
      expect(headers["x-opencode-session"]).toMatch(OPENCODE_SESSION_REGEX);
      expect(headers["session-id"]).toBe(headers["x-opencode-session"]);
      expect(headers["x-session-id"]).toBe(headers["x-opencode-session"]);
      expect(headers["x-opencode-request"]).toMatch(/^msg_[0-9a-f]{8}8ffe[0-9a-zA-Z]{14}$/);
    });

    it("preserves valid session ID passed via incomingHeaders", () => {
      const validId = "ses_abcdef018ffe0123456789abcd";
      const headers = buildZenHeaders({ "x-opencode-session": validId });

      expect(headers["x-opencode-session"]).toBe(validId);
      expect(headers["session-id"]).toBe(validId);
      expect(headers["x-session-id"]).toBe(validId);
      expect(headers["x-opencode-request"]).toBe("msg_abcdef018ffe0123456789abcd");
    });

    it("preserves valid session ID passed via standard Fetch Headers object", () => {
      const validId = "ses_abcdef018ffe0123456789abcd";
      const incoming = new Headers({ "x-opencode-session": validId });
      const headers = buildZenHeaders(incoming);

      expect(headers["x-opencode-session"]).toBe(validId);
      expect(headers["session-id"]).toBe(validId);
      expect(headers["x-session-id"]).toBe(validId);
      expect(headers["x-opencode-request"]).toBe("msg_abcdef018ffe0123456789abcd");
      expect(headers["User-Agent"]).toBeDefined();
    });

    it("preserves valid session ID passed via explicit parameter", () => {
      const validId = "ses_fedcba988ffeaBcDeFgHiJkLmN";
      const headers = buildZenHeaders(undefined, validId);

      expect(headers["x-opencode-session"]).toBe(validId);
      expect(headers["session-id"]).toBe(validId);
      expect(headers["x-session-id"]).toBe(validId);
      expect(headers["x-opencode-request"]).toBe("msg_fedcba988ffeaBcDeFgHiJkLmN");
    });

    it("replaces invalid session ID with a freshly generated valid session ID", () => {
      const invalidId = "invalid-session-12345";
      const headers = buildZenHeaders({ "session-id": invalidId });

      expect(headers["x-opencode-session"]).not.toBe(invalidId);
      expect(headers["x-opencode-session"]).toMatch(OPENCODE_SESSION_REGEX);
      expect(headers["session-id"]).toBe(headers["x-opencode-session"]);
      expect(headers["x-session-id"]).toBe(headers["x-opencode-session"]);
    });
  });

  describe("getZenProbeTools", () => {
    it("returns 6 standard OpenCode probe tools", () => {
      const tools = getZenProbeTools();
      expect(tools.length).toBe(6);

      const names = tools.map((t) => (t.function as { name: string }).name);
      expect(names).toEqual(["bash", "read", "write", "edit", "glob", "grep"]);

      for (const tool of tools) {
        expect(tool.type).toBe("function");
        const fn = tool.function as { name: string; description: string; parameters: any };
        expect(typeof fn.name).toBe("string");
        expect(typeof fn.description).toBe("string");
        expect(fn.parameters).toBeDefined();
        expect(Array.isArray(fn.parameters.required)).toBe(true);
      }
    });

    it("returns fresh clones on successive calls", () => {
      const tools1 = getZenProbeTools();
      const tools2 = getZenProbeTools();
      expect(tools1).not.toBe(tools2);
      expect(tools1[0]).not.toBe(tools2[0]);
    });
  });

  describe("adaptZenPayload", () => {
    it("injects probe tools when tools are missing or empty", () => {
      const p1 = adaptZenPayload({ model: "test-model" });
      expect(p1.adaptedBody.tools).toHaveLength(6);
      expect(p1.requiresAccumulation).toBe(true);
      expect(p1.adaptedBody.stream).toBe(true);

      const p2 = adaptZenPayload({ model: "test-model", tools: [] });
      expect(p2.adaptedBody.tools).toHaveLength(6);
    });

    it("preserves existing tools when provided", () => {
      const customTools = [{ type: "function", function: { name: "my_tool" } }];
      const adapted = adaptZenPayload({ model: "test-model", tools: customTools });
      expect(adapted.adaptedBody.tools).toEqual(customTools);
    });

    it("sets stream: true and requiresAccumulation: true when body.stream is falsy", () => {
      const r1 = adaptZenPayload({ model: "test-model", stream: false });
      expect(r1.requiresAccumulation).toBe(true);
      expect(r1.adaptedBody.stream).toBe(true);

      const r2 = adaptZenPayload({ model: "test-model" });
      expect(r2.requiresAccumulation).toBe(true);
      expect(r2.adaptedBody.stream).toBe(true);
    });

    it("keeps requiresAccumulation: false when body.stream is already true", () => {
      const r = adaptZenPayload({ model: "test-model", stream: true });
      expect(r.requiresAccumulation).toBe(false);
      expect(r.adaptedBody.stream).toBe(true);
    });
  });

  describe("accumulateZenStreamToCompletion", () => {
    function createMockStream(chunks: string[]): ReadableStream<Uint8Array> {
      const encoder = new TextEncoder();
      return new ReadableStream<Uint8Array>({
        start(controller) {
          for (const chunk of chunks) {
            controller.enqueue(encoder.encode(chunk));
          }
          controller.close();
        },
      });
    }

    it("accumulates text content and reasoning content from SSE stream", async () => {
      const sseChunks = [
        `data: {"id":"chatcmpl-123","model":"zen-test","choices":[{"index":0,"delta":{"role":"assistant","content":"Hello "},"finish_reason":null}]}\n\n`,
        `: keep-alive\n\n`,
        `data: {"id":"chatcmpl-123","model":"zen-test","choices":[{"index":0,"delta":{"reasoning_content":"Thinking... "},"finish_reason":null}]}\n\n`,
        `data: {"id":"chatcmpl-123","model":"zen-test","choices":[{"index":0,"delta":{"content":"world!","reasoning_content":"Done thinking."},"finish_reason":"stop"}]}\n\n`,
        `data: {"id":"chatcmpl-123","model":"zen-test","choices":[],"usage":{"prompt_tokens":10,"completion_tokens":15,"total_tokens":25}}\n\n`,
        `data: [DONE]\n\n`,
      ];

      const stream = createMockStream(sseChunks);
      const res = await accumulateZenStreamToCompletion(stream, "zen-test");

      expect(res.id).toBe("chatcmpl-123");
      expect(res.object).toBe("chat.completion");
      expect(res.model).toBe("zen-test");
      expect(res.choices).toHaveLength(1);
      expect(res.choices[0].finish_reason).toBe("stop");
      expect(res.choices[0].message.role).toBe("assistant");
      expect(res.choices[0].message.content).toBe("Hello world!");
      expect(res.choices[0].message.reasoning_content).toBe("Thinking... Done thinking.");
      expect(res.usage).toEqual({
        prompt_tokens: 10,
        completion_tokens: 15,
        total_tokens: 25,
      });
    });

    it("accumulates chunked tool calls across multiple stream events", async () => {
      const sseChunks = [
        `data: {"id":"chatcmpl-tc-1","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"id":"call_001","type":"function","function":{"name":"read","arguments":""}}]},"finish_reason":null}]}\n\n`,
        `data: {"id":"chatcmpl-tc-1","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"{\\"filePath\\": "}}]},"finish_reason":null}]}\n\n`,
        `data: {"id":"chatcmpl-tc-1","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"\\"/tmp/foo.txt\\"}"}}]},"finish_reason":"tool_calls"}]}\n\n`,
        `data: [DONE]\n\n`,
      ];

      const stream = createMockStream(sseChunks);
      const res = await accumulateZenStreamToCompletion(stream, "zen-test");

      expect(res.id).toBe("chatcmpl-tc-1");
      expect(res.choices[0].finish_reason).toBe("tool_calls");
      expect(res.choices[0].message.content).toBeNull();
      expect(res.choices[0].message.tool_calls).toEqual([
        {
          id: "call_001",
          type: "function",
          function: {
            name: "read",
            arguments: '{"filePath": "/tmp/foo.txt"}',
          },
        },
      ]);
    });

    it("handles multiple tool calls in a stream", async () => {
      const sseChunks = [
        `data: {"id":"chatcmpl-multi","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"id":"c1","type":"function","function":{"name":"read","arguments":"{\\"filePath\\":\\"a\\"}"}},{"index":1,"id":"c2","type":"function","function":{"name":"write","arguments":"{\\"content\\":\\"b\\"}"}}]},"finish_reason":"tool_calls"}]}\n\n`,
        `data: [DONE]\n\n`,
      ];

      const stream = createMockStream(sseChunks);
      const res = await accumulateZenStreamToCompletion(stream, "zen-test");

      expect(res.choices[0].message.tool_calls).toHaveLength(2);
      expect(res.choices[0].message.tool_calls[0].id).toBe("c1");
      expect(res.choices[0].message.tool_calls[1].id).toBe("c2");
    });

    it("generates tool call ID if missing and handles system_fingerprint", async () => {
      const sseChunks = [
        `data: {"id":"chatcmpl-auto-tc","system_fingerprint":"fp_12345","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"name":"bash","arguments":"ls -la"}}]},"finish_reason":"stop"}]}\n`,
        `: comment line to ignore\n`,
        `data: malformed-not-json\n\n`,
        `data: [DONE]\n`,
      ];

      const stream = createMockStream(sseChunks);
      const res = await accumulateZenStreamToCompletion(stream, "zen-test");

      expect(res.id).toBe("chatcmpl-auto-tc");
      expect(res.system_fingerprint).toBe("fp_12345");
      expect(res.choices[0].message.tool_calls).toHaveLength(1);
      expect(res.choices[0].message.tool_calls[0].id).toMatch(/^call_[0-9a-zA-Z]{24}$/);
      expect(res.choices[0].message.tool_calls[0].function.name).toBe("bash");
      expect(res.choices[0].message.tool_calls[0].function.arguments).toBe("ls -la");
      // Fallback usage
      expect(res.usage).toEqual({
        prompt_tokens: 0,
        completion_tokens: 0,
        total_tokens: 0,
      });
    });
  });
});
